# A sample Gemfile
source "https://rubygems.org"

group :test do
  gem 'rspec', '~> 3.0'
  gem 'capybara'
  gem 'poltergeist'
  gem 'turnip'
  gem 'selenium-webdriver'
  gem 'headless'
end

# テストデータ生成に使う
gem 'aws-sdk', '~> 2', :require => true
gem 'elasticsearch', '~> 1.0', :require => true

